version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_EXT_PORT}:${UI_INT_PORT}/tcp
    networks:
      front_net:
        aliases:
          - ui

  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post

  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment

volumes:
  post_db:

networks:
  back_net:
    driver: bridge
    ipam:
      config:
      - subnet: ${BACK_NET}

  front_net:
    driver: bridge
    ipam:
      config:
      - subnet: ${FRONT_NET}



